export const theories = {
  gwt: {
    name: "Global Workspace Theory",
    description:
      "GWT posits that consciousness arises when information becomes globally available across specialized processors in the brain.",
  },
  iit: {
    name: "Integrated Information Theory",
    description:
      "IIT quantifies consciousness as integrated information (Φ) generated by a system over and above its parts.",
  },
  pp: {
    name: "Predictive Processing",
    description:
      "PP frames the brain as a prediction machine minimizing surprise (prediction error) through hierarchical Bayesian inference.",
  },
} as const
