export const theories = {
  gwt: {
    name: "Global Workspace Theory",
    description:
      "GWT posits that consciousness arises when information becomes globally available across specialized processors in the brain.",
    fullDescription:
      "Global Workspace Theory, developed by Bernard Baars, proposes that consciousness is a global workspace where information from various specialized brain systems becomes available for coordinated processing. This theory explains why we can only be consciously aware of a limited amount of information at any given time, despite the brain processing vast amounts of data unconsciously.",
    keyPoints: [
      "Information must be globally broadcast to multiple systems",
      "Limited capacity of conscious awareness",
      "Unconscious processes feed into the workspace",
      "Explains attention and focus",
    ],
    references: [
      "Baars, B. J. (1988). A Cognitive Theory of Consciousness.",
      "Baars, B. J. (2005). Global Workspace Theory of Consciousness.",
    ],
  },
  iit: {
    name: "Integrated Information Theory",
    description:
      "IIT quantifies consciousness as integrated information (Φ) generated by a system over and above its parts.",
    fullDescription:
      "Integrated Information Theory, developed by Giulio Tononi, proposes that consciousness corresponds to integrated information in a system. The theory quantifies consciousness using Phi (Φ), which measures how much information is integrated in a system beyond what would be expected from its individual parts.",
    keyPoints: [
      "Consciousness = Integrated Information (Φ)",
      "Systems must have both differentiation and integration",
      "Applies to any physical system, not just brains",
      "Provides mathematical framework for consciousness",
    ],
    references: [
      "Tononi, G. (2004). An Information Integration Theory of Consciousness.",
      "Tononi, G., Boly, M., Massimini, M., & Koch, C. (2016). Integrated Information Theory.",
    ],
  },
  pp: {
    name: "Predictive Processing",
    description:
      "PP frames the brain as a prediction machine minimizing surprise (prediction error) through hierarchical Bayesian inference.",
    fullDescription:
      "Predictive Processing proposes that the brain is fundamentally a prediction machine that constantly generates predictions about incoming sensory data and updates these predictions based on prediction errors. This framework unifies perception, action, and cognition under a single principle: minimizing surprise or prediction error.",
    keyPoints: [
      "Brain generates hierarchical predictions",
      "Perception is active inference, not passive reception",
      "Prediction errors drive learning",
      "Explains hallucinations and illusions",
    ],
    references: [
      "Friston, K. (2010). The Free-Energy Principle: A Unified Brain Theory.",
      "Clark, A. (2013). Whatever Next? Predictive Brains, Situated Agents, and the Future of Cognitive Science.",
    ],
  },
} as const
